// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlVrLL-Zn-robvAJhwOfJAW4oMULFJmPI',
    appId: '1:925064393005:web:d917982e9f9efb8e45a3a4',
    messagingSenderId: '925064393005',
    projectId: 'hasartespit-bfe7b',
    authDomain: 'hasartespit-bfe7b.firebaseapp.com',
    storageBucket: 'hasartespit-bfe7b.appspot.com',
    measurementId: 'G-7TC1Z0X8G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFghLDE2E_inpikihlXHbHiw1jD7lYNk4',
    appId: '1:925064393005:android:8806dbdafece7efa45a3a4',
    messagingSenderId: '925064393005',
    projectId: 'hasartespit-bfe7b',
    storageBucket: 'hasartespit-bfe7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD16yCUd7nIQdY4xvVFMobwIjhoXhxRzMs',
    appId: '1:925064393005:ios:9638cf2c189ddc0c45a3a4',
    messagingSenderId: '925064393005',
    projectId: 'hasartespit-bfe7b',
    storageBucket: 'hasartespit-bfe7b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD16yCUd7nIQdY4xvVFMobwIjhoXhxRzMs',
    appId: '1:925064393005:ios:d32239475a870d4345a3a4',
    messagingSenderId: '925064393005',
    projectId: 'hasartespit-bfe7b',
    storageBucket: 'hasartespit-bfe7b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
